-- Drop existing tables (development only)
DROP TABLE IF EXISTS attendance_logs CASCADE;

DROP TABLE IF EXISTS subject_students CASCADE;

DROP TABLE IF EXISTS subjects CASCADE;

DROP TABLE IF EXISTS students CASCADE;

DROP TABLE IF EXISTS teachers CASCADE;

-- Teachers

CREATE TABLE IF NOT EXISTS teachers (

teacher_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

username TEXT UNIQUE NOT NULL,

password TEXT NOT NULL,

name TEXT,

created_at TIMESTAMPTZ DEFAULT NOW()

);

-- Students

CREATE TABLE IF NOT EXISTS students (

student_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

name TEXT NOT NULL,

face_embedding JSONB,

voice_embedding JSONB,

created_at TIMESTAMPTZ DEFAULT NOW()

);

-- Subjects

CREATE TABLE IF NOT EXISTS subjects (

subject_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

name TEXT NOT NULL,

subject_code TEXT UNIQUE NOT NULL,

section TEXT,

teacher_id BIGINT REFERENCES teachers(teacher_id) ON DELETE SET NULL,

created_at TIMESTAMPTZ DEFAULT NOW()

);

-- Enrollment table expected by the app

CREATE TABLE IF NOT EXISTS subject_students (

id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

student_id BIGINT REFERENCES students(student_id) ON DELETE CASCADE,

subject_id BIGINT REFERENCES subjects(subject_id) ON DELETE CASCADE,

enrolled_at TIMESTAMPTZ DEFAULT NOW(),

UNIQUE(student_id, subject_id)

);

-- Attendance table expected by the app

CREATE TABLE IF NOT EXISTS attendance_logs (

attendance_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

student_id BIGINT REFERENCES students(student_id) ON DELETE CASCADE,

subject_id BIGINT REFERENCES subjects(subject_id) ON DELETE CASCADE,

recorded_at TIMESTAMPTZ DEFAULT NOW(),

is_present BOOLEAN DEFAULT FALSE

);

-- Permissions / RLS (development convenience)

ALTER TABLE teachers DISABLE ROW LEVEL SECURITY;

ALTER TABLE students DISABLE ROW LEVEL SECURITY;

ALTER TABLE subjects DISABLE ROW LEVEL SECURITY;

ALTER TABLE subject_students DISABLE ROW LEVEL SECURITY;

ALTER TABLE attendance_logs DISABLE ROW LEVEL SECURITY;

GRANT ALL ON ALL TABLES IN SCHEMA public TO postgres, anon, authenticated, service_role;

GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO postgres, anon, authenticated, service_role;
