apiVersion: v1
kind: Service
metadata:
  name: gazehum-service
spec:
  sessionAffinity: ClientIP
  selector:
    app: gazehum
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
  type: LoadBalancer
