SUPABASE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRrbGNwZ3Jmcmtod29wamliaGl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg2NzI2OTksImV4cCI6MjA5NDI0ODY5OX0.nPx-51e-m0lxzA4AXVH8WS1wrR4WBlL1yUDxEXEOPNg"

SUPABASE_URL="https://tklcpgrfrkhwopjibhiw.supabase.co"